In [5]:
import numpy as numpy
import random

from Sudoku import Sudoku


sudo = Sudoku()


# sudo.grid = numpy.array([[2, 5, 6, 8, 3, 0, 9, 0, 1],
#                          [0, 1, 0, 0, 0, 4, 0, 0, 0],
#                          [4, 0, 7, 0, 0, 0, 2, 0, 8],
#                          [0, 0, 5, 2, 0, 0, 0, 0, 0],
#                          [0, 0, 0, 0, 9, 8, 1, 0, 0],
#                          [0, 4, 0, 0, 0, 3, 0, 0, 0],
#                          [0, 0, 0, 3, 6, 0, 0, 7, 2],
#                          [0, 7, 0, 0, 0, 0, 0, 0, 3],
#                          [9, 0, 3, 0, 0, 0, 6, 0, 4]])



# sudo.grid = numpy.array = [
#         [4, 0, 0, 0, 1, 0, 0, 3, 0],
#         [0, 2, 0, 7, 0, 0, 0, 0, 0],
#         [0, 0, 0, 0, 0, 0, 0, 0, 0],
#         [5, 0, 8, 0, 3, 0, 0, 0, 0],
#         [0, 0, 0, 0, 0, 0, 2, 0, 9],
#         [0, 0, 0, 0, 8, 0, 7, 0, 0],
#         [3, 0, 0, 0, 0, 0, 0, 1, 0],
#         [0, 0, 0, 2, 0, 0, 6, 0, 0],
#         [0, 0, 0, 6, 0, 0, 0, 0, 0]
#     ]

# sudo.grid = numpy.array([
#     [5, 0, 0, 0, 7, 0, 0, 0, 0],
#     [6, 0, 0, 1, 0, 0, 0, 0, 0],
#     [0, 9, 0, 0, 0, 0, 0, 6, 0],
#     [8, 0, 0, 0, 6, 0, 0, 0, 3],
#     [0, 0, 0, 8, 0, 0, 0, 0, 1],
#     [7, 0, 0, 0, 2, 0, 0, 0, 0],
#     [0, 0, 0, 0, 0, 0, 2, 8, 0],
#     [0, 0, 0, 4, 0, 9, 0, 0, 5],
#     [0, 0, 0, 0, 8, 0, 0, 0, 9]
# ])



sudo.grid =  numpy.zeros(shape=(9,9)) ## tu peux donner autres grilles

import time
start_time = time.time()
# sudo.solve()
sudo.solver()
print(sudo.grid)
end_time = time.time()
total_time = end_time - start_time
print("Time: ", total_time)

[[1. 2. 3. 4. 5. 6. 7. 8. 9.]
 [4. 5. 6. 7. 8. 9. 1. 2. 3.]
 [7. 8. 9. 1. 2. 3. 4. 5. 6.]
 [2. 1. 4. 3. 6. 5. 8. 9. 7.]
 [3. 6. 5. 8. 9. 7. 2. 1. 4.]
 [8. 9. 7. 2. 1. 4. 3. 6. 5.]
 [5. 3. 1. 6. 4. 2. 9. 7. 8.]
 [6. 4. 2. 9. 7. 8. 5. 3. 1.]
 [9. 7. 8. 5. 3. 1. 6. 4. 2.]]
Time:  0.06365513801574707


In [7]:
def creator(self,difficulty):
        if difficulty == 1 or difficulty  == 2 or difficulty  == 3 :
            self.grid_1line()
            self.solver()
            for i in range(0,40 + difficulty *6 ):
                self.grid[random.randint(0,8)][random.randint(0,8)]=0
            return
        else:
            print ('Veuillez rentrer un niveau de difficulté : facile , moyen ou difficile')